spring.application.name=chat-server

spring.datasource.url=jdbc:postgresql://localhost:5432/chat
spring.datasource.username=chat
spring.datasource.password=chat
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.threads.virtual.enabled=true

chat.ws.port=8081
